FROM registry.access.redhat.com/ubi9/python-312:9.8-1780506588 as builder

COPY --chown=default:0 . .

RUN pip install setuptools "setuptools_scm>=8"
RUN pip wheel --no-deps --no-build-isolation -w dist ./bonfire_mcp

FROM registry.access.redhat.com/ubi9-minimal:9.8-1780378819

ENV APP_ROOT=/opt/bonfire

ENV PYTHON_VERSION=3.12 \
    PATH=$APP_ROOT/.local/bin/:$PATH \
    PYTHONUNBUFFERED=1 \
    PYTHONIOENCODING=UTF-8 \
    LANG=en_US.UTF-8 \
    CNB_USER_ID=1000 \
    CNB_GROUP_ID=0 \
    PIP_NO_CACHE_DIR=off

RUN microdnf install -y python3.12 python3.12-pip shadow-utils && \
    microdnf clean all

RUN useradd -r -u 1001 -g 0 -m -d $APP_ROOT -s /bin/bash bonfire && \
    chmod 755 $APP_ROOT && \
    mkdir -p $APP_ROOT/.kube && chown 1001:0 $APP_ROOT/.kube

USER 1001
WORKDIR $APP_ROOT

COPY --from=builder /opt/app-root/src/dist/crc_bonfire_mcp*.whl .

RUN WHEEL=$(ls crc_bonfire_mcp*.whl) && pip3.12 install "$WHEEL" && rm "$WHEEL"

ENTRYPOINT [ "bonfire-mcp" ]
