apiVersion: v1
kind: Template
metadata:
  name: default-iqe-cji

objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdJobInvocation
  metadata:
    name: ${NAME}
  spec:
    appName: ${APP_NAME}
    testing:
      iqe:
        debug: ${{DEBUG}}
        imageTag: ${IMAGE_TAG}
        env:
          IQE_MARKER_EXPRESSION: ${MARKER}
          IQE_FILTER_EXPRESSION: ${FILTER}
          IQE_PLUGINS: ${PLUGINS}
          ENV_FOR_DYNACONF: ${ENV_NAME}
          IQE_REQUIREMENTS: ${{REQUIREMENTS}}
          IQE_REQUIREMENTS_PRIORITY: ${{REQUIREMENTS_PRIORITY}}
          IQE_TEST_IMPORTANCE: ${{TEST_IMPORTANCE}}
          IQE_PARALLEL_ENABLED: ${{PARALLEL_ENABLED}}
          IQE_PARALLEL_WORKER_COUNT: ${{PARALLEL_WORKER_COUNT}}
          IQE_RP_ARGS: ${{RP_ARGS}}
          IQE_IBUTSU_SOURCE: ${{IBUTSU_SOURCE}}
        ui:
          selenium:
            deploy: ${{DEPLOY_SELENIUM}}

parameters:
- name: NAME
  required: true
- name: APP_NAME
  required: true
- name: DEBUG
  value: "false"
- name: IMAGE_TAG
  value: ""
- name: MARKER
  value: ""
- name: FILTER
  value: ""
- name: ENV_NAME
  value: "clowder_smoke"
  required: true
- name: REQUIREMENTS
  value: "[]"
- name: REQUIREMENTS_PRIORITY
  value: "[]"
- name: TEST_IMPORTANCE
  value: "[]"
- name: PLUGINS
  value: ""
- name: DEPLOY_SELENIUM
  value: "false"
- name: PARALLEL_ENABLED
  value: "true"
- name: PARALLEL_WORKER_COUNT
  value: "2"
- name: RP_ARGS
  value: ""
- name: IBUTSU_SOURCE
  value: ""
