apiVersion: v1
kind: Template
metadata:
  name: default-iqe-cji

objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdJobInvocation
  metadata:
    name: ${NAME}
  spec:
    appName: ${APP_NAME}
    testing:
      iqe:
        debug: ${{DEBUG}}
        imageTag: ${IMAGE_TAG}
        marker: ${MARKER}
        filter: ${FILTER}
        plugins: ${PLUGINS}
        dynaconfEnvName: ${ENV_NAME}
        requirements: ${{REQUIREMENTS}}
        requirementsPriority: ${{REQUIREMENTS_PRIORITY}}
        testImportance: ${{TEST_IMPORTANCE}}
        parallelEnabled: ${{PARALLEL_ENABLED}}
        parallelWorkerCount: ${{PARALLEL_WORKER_COUNT}}
        rpArgs: ${{RP_ARGS}}
        ibutsuSource: ${{IBUTSU_SOURCE}}
        ui:
          selenium:
            deploy: ${{DEPLOY_SELENIUM}}

parameters:
- name: NAME
  required: true
- name: APP_NAME
  required: true
- name: DEBUG
  value: "false"
- name: IMAGE_TAG
  value: ""
- name: MARKER
  value: ""
- name: FILTER
  value: ""
- name: ENV_NAME
  value: "clowder_smoke"
  required: true
- name: REQUIREMENTS
  value: "[]"
- name: REQUIREMENTS_PRIORITY
  value: "[]"
- name: TEST_IMPORTANCE
  value: "[]"
- name: PLUGINS
  value: ""
- name: DEPLOY_SELENIUM
  value: "false"
- name: PARALLEL_ENABLED
  value: "true"
- name: PARALLEL_WORKER_COUNT
  value: "2"
- name: RP_ARGS
  value: ""
- name: IBUTSU_SOURCE
  value: ""

