apiVersion: v1
kind: Template
metadata:
  name: ephemeral-clowdenvironment

objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdEnvironment
  metadata:
    name: ${ENV_NAME}
  spec:
    targetNamespace: ${NAMESPACE}
    resourceDefaults:
      limits:
        cpu: 300m
        memory: 256Mi
      requests:
        cpu: 30m
        memory: 128Mi
    providers:
      pullSecrets:
        - name: ${PULL_SECRET_NAME}
          namespace: ${NAMESPACE}
      testing:
        # Level of access the testing pod has in the namespace
        k8sAccessLevel: edit
        # How much environment configuration the testing pod can see
        configAccess: environment
        iqe:
          # Base image for iqe-tests
          imageBase: "quay.io/cloudservices/iqe-tests"
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 256Mi
      web:
        port: 8000
        privatePort: 10000
        mode: operator
      featureFlags:
        mode: local
      metrics:
        port: 9000
        path: "/metrics"
        prometheus:
          deploy: true
        mode: operator
      kafka:
        mode: operator
        # disable tls/auth for now until core apps are ready
        enableLegacyStrimzi: true
        cluster:
          version: "3.4.0"
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 600Mi
        connect:
          version: "3.4.0"
          image: "quay.io/cloudservices/xjoin-kafka-connect-strimzi:latest"
      db:
        mode: local
      logging:
        mode: none
      objectStore:
        mode: minio
      inMemoryDb:
        mode: redis
parameters:
- name: NAMESPACE
  description: Namespace that ClowdEnvironment components will be deployed to
- name: ENV_NAME
  description: Name of the ClowdEnvironment
  required: true
- name: PULL_SECRET_NAME
  value: quay-cloudservices-pull
