apiVersion: v1
kind: Template
metadata:
  name: default-reservation

objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: NamespaceReservation
  metadata:
    name: ${NAME}
    labels:
      requester: ${REQUESTER}
  spec:
    duration: ${DURATION}
    requester: ${REQUESTER}
    pool-type: ${POOLTYPE}

parameters:
- name: DURATION
  required: true
- name: REQUESTER
  required: true
- name: NAME
  required: true
- name: POOLTYPE
  required: true
