package ephemeral

import (
	"context"
	"strings"
	"testing"
)

func TestReserve_HappyPath(t *testing.T) {
	res := sampleReservation()
	calls := 0
	mc := noopClient()
	mc.getReservationFn = func(_ context.Context, _ string) (map[string]any, error) {
		calls++
		switch calls {
		case 1:
			return nil, nil // no existing reservation
		case 2:
			return res, nil // poll returns namespace
		default:
			return res, nil // final get
		}
	}
	mc.createReservationFn = func(_ context.Context, _ map[string]any) (map[string]any, error) {
		return res, nil
	}

	result, err := Reserve(context.Background(), mc, ReserveOptions{
		Name:      "test-reservation",
		Duration:  "1h",
		Requester: "test-user",
		Pool:      "default",
		Timeout:   10,
	})
	mustNotErr(t, err)
	if result.Name != "test-reservation" {
		t.Errorf("Name = %q, want %q", result.Name, "test-reservation")
	}
	if result.Namespace != "ephemeral-abc123" {
		t.Errorf("Namespace = %q, want %q", result.Namespace, "ephemeral-abc123")
	}
	if result.Requester != "test-user" {
		t.Errorf("Requester = %q, want %q", result.Requester, "test-user")
	}
	if result.Pool != "default" {
		t.Errorf("Pool = %q, want %q", result.Pool, "default")
	}
}

func TestReserve_DuplicateNameRaises(t *testing.T) {
	mc := noopClient()
	mc.getReservationFn = func(_ context.Context, _ string) (map[string]any, error) {
		return sampleReservation(), nil // already exists
	}

	_, err := Reserve(context.Background(), mc, ReserveOptions{Name: "test-reservation"})
	if err == nil {
		t.Fatal("expected error, got nil")
	}
	if !strings.Contains(err.Error(), "already exists") {
		t.Errorf("error %q should contain 'already exists'", err.Error())
	}
}

func TestReserve_AutoGeneratedName(t *testing.T) {
	res := sampleReservation()
	calls := 0
	mc := noopClient()
	mc.getReservationFn = func(_ context.Context, _ string) (map[string]any, error) {
		calls++
		if calls == 1 {
			return nil, nil
		}
		return res, nil
	}
	mc.createReservationFn = func(_ context.Context, _ map[string]any) (map[string]any, error) {
		return res, nil
	}

	result, err := Reserve(context.Background(), mc, ReserveOptions{
		Duration:  "1h",
		Requester: "test-user",
		Timeout:   10,
	})
	mustNotErr(t, err)
	if !strings.HasPrefix(result.Name, "bonfire-reservation-") {
		t.Errorf("Name %q should start with 'bonfire-reservation-'", result.Name)
	}
}

func TestReserve_DefaultRequesterFromWhoami(t *testing.T) {
	res := sampleReservation()
	calls := 0
	mc := noopClient()
	mc.getReservationFn = func(_ context.Context, _ string) (map[string]any, error) {
		calls++
		if calls == 1 {
			return nil, nil
		}
		return res, nil
	}
	mc.createReservationFn = func(_ context.Context, _ map[string]any) (map[string]any, error) {
		return res, nil
	}
	// Whoami default returns "test_at_user.com" from noopClient

	result, err := Reserve(context.Background(), mc, ReserveOptions{
		Name:    "test-res",
		Timeout: 10,
	})
	mustNotErr(t, err)
	if result.Requester != "test_at_user.com" {
		t.Errorf("Requester = %q, want %q", result.Requester, "test_at_user.com")
	}
}

func TestRelease_ByName(t *testing.T) {
	res := sampleReservation()
	mc := noopClient()
	mc.getReservationFn = func(_ context.Context, _ string) (map[string]any, error) {
		return res, nil
	}
	var patchedName string
	var patchedBody map[string]any
	mc.patchReservationFn = func(_ context.Context, name string, patch map[string]any) (map[string]any, error) {
		patchedName = name
		patchedBody = patch
		return res, nil
	}

	result, err := Release(context.Background(), mc, ReleaseOptions{Name: "test-reservation"})
	mustNotErr(t, err)
	if result.Name != "test-reservation" {
		t.Errorf("Name = %q, want %q", result.Name, "test-reservation")
	}
	if !result.Released {
		t.Error("Released should be true")
	}
	if patchedName != "test-reservation" {
		t.Errorf("patched name = %q, want %q", patchedName, "test-reservation")
	}
	spec, _ := patchedBody["spec"].(map[string]any)
	if spec["duration"] != "0s" {
		t.Errorf("patch spec.duration = %v, want '0s'", spec["duration"])
	}
}

func TestRelease_ByNamespace(t *testing.T) {
	res := sampleReservation()
	mc := noopClient()
	mc.listReservationsFn = func(_ context.Context, _ string) ([]map[string]any, error) {
		return []map[string]any{res}, nil
	}
	mc.patchReservationFn = func(_ context.Context, _ string, _ map[string]any) (map[string]any, error) {
		return res, nil
	}

	result, err := Release(context.Background(), mc, ReleaseOptions{Namespace: "ephemeral-abc123"})
	mustNotErr(t, err)
	if result.Name != "test-reservation" {
		t.Errorf("Name = %q, want %q", result.Name, "test-reservation")
	}
}

func TestRelease_UnknownNameRaises(t *testing.T) {
	mc := noopClient()
	mc.getReservationFn = func(_ context.Context, _ string) (map[string]any, error) {
		return nil, nil
	}

	_, err := Release(context.Background(), mc, ReleaseOptions{Name: "nonexistent"})
	if err == nil {
		t.Fatal("expected error, got nil")
	}
	if !strings.Contains(err.Error(), "not found") {
		t.Errorf("error %q should contain 'not found'", err.Error())
	}
}

func TestRelease_NoArgsRaises(t *testing.T) {
	mc := noopClient()
	_, err := Release(context.Background(), mc, ReleaseOptions{})
	if err == nil {
		t.Fatal("expected error, got nil")
	}
	if !strings.Contains(err.Error(), "Must provide") {
		t.Errorf("error %q should contain 'Must provide'", err.Error())
	}
}

func TestExtend_HappyPath(t *testing.T) {
	res := sampleReservation() // duration=1h, state=active
	mc := noopClient()
	mc.listReservationsFn = func(_ context.Context, _ string) ([]map[string]any, error) {
		return []map[string]any{res}, nil
	}
	var patchedBody map[string]any
	mc.patchReservationFn = func(_ context.Context, _ string, patch map[string]any) (map[string]any, error) {
		patchedBody = patch
		return res, nil
	}

	result, err := Extend(context.Background(), mc, "ephemeral-abc123", "30m")
	mustNotErr(t, err)
	if result.Name != "test-reservation" {
		t.Errorf("Name = %q, want %q", result.Name, "test-reservation")
	}
	if result.NewDuration != "1h30m0s" {
		t.Errorf("NewDuration = %q, want %q", result.NewDuration, "1h30m0s")
	}
	spec, _ := patchedBody["spec"].(map[string]any)
	if spec["duration"] != "1h30m0s" {
		t.Errorf("patch spec.duration = %v, want '1h30m0s'", spec["duration"])
	}
}

func TestExtend_ExpiredRaises(t *testing.T) {
	expired := map[string]any{
		"metadata": map[string]any{"name": "expired-res"},
		"spec":     map[string]any{"duration": "1h", "requester": "user", "pool": "default"},
		"status":   map[string]any{"state": "expired", "namespace": "ephemeral-expired"},
	}
	mc := noopClient()
	mc.listReservationsFn = func(_ context.Context, _ string) ([]map[string]any, error) {
		return []map[string]any{expired}, nil
	}

	_, err := Extend(context.Background(), mc, "ephemeral-expired", "1h")
	if err == nil {
		t.Fatal("expected error, got nil")
	}
	if !strings.Contains(err.Error(), "expired") {
		t.Errorf("error %q should contain 'expired'", err.Error())
	}
}

func TestExtend_NotFoundRaises(t *testing.T) {
	mc := noopClient()
	mc.listReservationsFn = func(_ context.Context, _ string) ([]map[string]any, error) {
		return []map[string]any{}, nil
	}

	_, err := Extend(context.Background(), mc, "nonexistent", "1h")
	if err == nil {
		t.Fatal("expected error, got nil")
	}
	if !strings.Contains(err.Error(), "No reservation found") {
		t.Errorf("error %q should contain 'No reservation found'", err.Error())
	}
}
