name: Publish crc-bonfire to PyPI

on: push

jobs:
  build:
    name: Build 📦
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install build dependencies
        run: |
          pip install build twine
      - name: Build sdist and wheel
        run: |
          python -m build
      - name: Twine check
        run: python -m twine check dist/*
      - name: Store artifacts
        uses: actions/upload-artifact@v3
        with:
          name: python-package-distributions
          path: dist/

  publish-to-testpypi:
    name: Publish to TestPyPI
    needs:
    - build
    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org/p/crc-bonfire

    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v3
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish distribution 📦 to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/          

  publish:
    name: Build and publish to PyPI
    if: startsWith(github.event.ref, 'refs/tags')
    runs-on: ubuntu-latest
    needs:
      - build
    environment:
      name: release
      url: https://pypi.org/p/crc-bonfire
    permissions:
      # mandatory for trusted publishing
      id-token: write

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v3
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
