name: Publish crc-bonfire to PyPI

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build-and-publish:
    name: Build and publish Python 🐍 distributions to PyPI
    if: startsWith(github.event.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to master
        uses: actions/checkout@master

      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Build Package and Check
        run: |
          python -m pip install --upgrade setuptools wheel twine
          python setup.py sdist bdist_wheel
          python -m twine check dist/*

      - name: Deploy to PyPi
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_token }}
