name: Publish crc-bonfire to PyPI

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build-and-publish:
    name: Build and publish to PyPI
    if: startsWith(github.event.ref, 'refs/tags')
    runs-on: ubuntu-20.04
    environment:
      name: release
      url: https://pypi.org/p/crc-bonfire
    permissions:
      # mandatory for trusted publishing
      id-token: write

    steps:
      - name: Checkout to master
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: Install build dependencies
        run: |
          pip install build twine

      - name: Build sdist and wheel
        run: |
          python -m build -o dist/

      - name: Twine check
        run: python -m twine check dist/*

      - name: Deploy to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
